name: flutter_core
description: "Flutter Core Project"
version: 2.0.3

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0
  intl: ^0.19.0
  collection: ^1.18.0
  dio: ^5.4.3+1
  sqflite: ^2.3.3
  shared_preferences: ^2.2.3

  #ui
  animations: ^2.0.7

  #utils
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  url_launcher: ^6.2.6
  app_settings: ^5.1.1

  #encryption
  encrypt: ^5.0.3
  permission_handler: ^11.3.1
  in_app_update: ^4.2.3
  huawei_hmsavailability: ^6.12.0+300

  #image
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter.flutter_core
        pluginClass: FlutterCorePlugin
      ios:
        pluginClass: FlutterCorePlugin
      linux:
        pluginClass: FlutterCorePlugin
      macos:
        pluginClass: FlutterCorePlugin
      windows:
        pluginClass: FlutterCorePluginCApi
      web:
        pluginClass: FlutterCoreWeb
        fileName: flutter_core_web.dart
